### PR TITLE
WIP: plot showing crossover points for pairs of sigma

### PR DESCRIPTION
**Pull request by vishaalprasad**

### CODE REVIEW

**Comment by vishaalprasad** [comment]
Here is a conceptual question for what we are trying to do. The code as written determines the crossover point for a set of sigmas as follows.

Find the mean standard deviation for sigma1 and sigma2 (for sake of simplicity, call these variables `sig1` and `sig2`).

Do a pointwise division between `sig1` and `sig2.` You get a variable (named `ratios`) with values similar to:

ratios =

>  Columns 1 through 9
> 
>    1.0206    1.0278    1.0376    1.0504    1.0648    1.0789    1.0921    1.1043    1.1132
> 
>  Columns 10 through 16
> 
>    1.1147    1.1118    1.1100    1.1056    1.0870    1.0418    0.9751

Look at the first value (this corresponds to the lowest frequency in CPI). If it's greater than 1, then look for the first CPI that has a frequency smaller than 1. If it's smaller than 1, look for the first CPI that has a frequency greater than 1. These are the crossover points.

However, if we look at the `ratios` array printed above, we can observe that beyond this crossover point, there is another value of note: 1.1147. This value is interesting because this is when the ratio is at a peak. Right now, we ignore the **shape** of the `ratios` array in favor of this crossover point. My question is --- is that exactly what we want to do? Do we care at all whether the peak was at 1.1147 or 1.60, or that it occurred at 4.2 CPI instead of 2.7 CPI?

**Comment by bcipolli** [comment]
This makes sense, I believe. As the second sigma increases (higher frequency bias), the crossover point decreases (more towards lower frequencies.

The plots would probably clean up if we only plot for sigma1 < sigma2. Otherwise, the direction of the cross-over effect will flip meaning (perhaps why you're getting some going up, and some going down).

I've made some code tweaks (some indenting, some simplification) that I'll send a PR for shortly.

**Comment by bcipolli** [comment]
@vishaalprasad Hmm, this is what I get when I run your script out of the box. My code reproduces this (but with color). Any idea how I can produce the figure you ran? It's not just the colors that are different.

image

**Comment by vishaalprasad** [comment]
@bcipolli, that is the same plot I get when I run the code out of box... sorry the image I posted was really misleading in that regard!

The one I sent earlier was on a 20x20 image with 34 connections and sigma=[2,4,6,8,10].
Run with these parameters, and you should replicate the original plot.

**Comment by bcipolli** [comment]
Got it. I also had to change the cpi to `4*[..]` to replicate. I've also blanked out half of the crossover values, to focus on the ones that should be decreasing (as discussed previously; it's a symmetric matrix, values decrease in one direction, increase in the other).

I will create a PR with my code shortly. Now that I've understood what's going on, I will focus with parameter setting - my guess is that as connection density (# connections / # pixels) change, so too should the frequency preferences.

Will need to address that later, busy day for me here!

image

**Comment by bcipolli** [comment]
p.s. I have also started using freqs as  `[1 2:2:12]`

**Comment by bcipolli** [comment]
Will merge this PR, so that the next one can be clearer.

**Pull request merged**
